'use strict';
const APP_VERSION='3.0.0';
const LAST_SESSION_KEY='nr509-v3-last-session';
const workflow=[
{id:'identifying',title:'Identifying Information & Historian Reliability',student:'Verify identity, identify the source of history, and assess reliability.',coach:'Confirm identity and whether the student established who is providing the history and reliability.'},
{id:'chief',title:'Chief Concern',student:'Obtain the reason for encounter in the patient’s own words.',coach:'Do not expand the story until the student clarifies the chief concern.'},
{id:'hpi',title:'History of Present Illness',student:'Develop the current problem using OLDCARTS/OPQRST, associated symptoms, pertinent negatives, prior episodes, and effect on function.',coach:'Answer only the HPI elements actually asked. Mark omissions rather than volunteering them.'},
{id:'medications',title:'Current Medications & Supplements',student:'Reconcile name, dose, route, frequency, indication, adherence, supplements, and last dose when relevant.',coach:'Require medication details rather than accepting “I take a pill.”'},
{id:'allergies',title:'Allergies & Exact Reactions',student:'Ask about medication, food, environmental, and latex allergies and the exact reaction.',coach:'Do not accept an allergy label without the reaction.'},
{id:'past',title:'Past Medical & Surgical History',student:'Collect illnesses, hospitalizations, surgeries, injuries, reproductive history when relevant, and major prior evaluations.',coach:'Release only the past-history items specifically assessed.'},
{id:'preventive',title:'Preventive Health & Immunizations',student:'Assess immunizations, screening, dental/vision care, and age-appropriate prevention.',coach:'Score whether prevention and immunizations were addressed.'},
{id:'family',title:'Family History',student:'Assess major familial conditions, ages/causes of death, and early-onset disease.',coach:'Hold important family risks until the student asks.'},
{id:'social',title:'Personal & Social History',student:'Assess living situation, occupation, tobacco, alcohol, substances, sexual health, safety, diet, activity, and sleep as appropriate.',coach:'Answer neutrally and score respectful, nonjudgmental questioning.'},
{id:'function',title:'Functional Assessment & Social Determinants',student:'Assess ADLs/IADLs, health literacy, transportation, food, housing, finances, support, safety, and access barriers.',coach:'Note whether the student connects social data to clinical care.'},
{id:'ros',title:'Review of Systems',student:'Complete the relevant systematic symptom screen without repeating the HPI.',coach:'Use focused yes/no answers; mark systems not assessed.'},
{id:'exam',title:'Physical Examination',student:'Perform the focused examination in a systematic sequence and identify urgent findings.',coach:'Release examination findings only when the correct maneuver is performed.'},
{id:'key',title:'Key Findings',student:'Select the most important positive and negative findings that shape the differential.',coach:'Score relevance rather than quantity.'},
{id:'problem',title:'Problem Statement',student:'State age, chief concern, key subjective findings, and key objective findings in one concise synthesis.',coach:'Check that the statement is concise and discriminating.'},
{id:'differential',title:'Differential Diagnoses',student:'Prioritize plausible diagnoses and identify cannot-miss alternatives.',coach:'Score prioritization and linkage to findings.'},
{id:'plan',title:'Management Plan',student:'State diagnostics, treatment, education, consultations, safety-net instructions, and follow-up.',coach:'Check completeness, safety, and whether the plan matches the working diagnosis.'},
{id:'debrief',title:'Debrief & Remediation',student:'Review missed and prompted elements and identify the next practice target.',coach:'Give targeted feedback and repeat the weakest portion.'}
];
const templates={
heent:{patient:{name:'Jordan Taylor',age:'24',pronouns:'she/her',historian:'Self; reliable',chief:'Severe sore throat',opening:'My throat feels like I am swallowing glass.',behavior:'Cooperative but uncomfortable.'},findings:[['hpi','Onset','Symptoms began three days ago.'],['hpi','Severity','Pain is 8/10 and worse with swallowing.'],['hpi','Associated symptoms','Fever, fatigue, and tender anterior cervical nodes are present.'],['ros','Pertinent negatives','No drooling, stridor, shortness of breath, rash, or inability to swallow liquids.'],['exam','Oropharynx','Tonsils are enlarged with patchy exudate.'],['exam','Respiratory status','Lungs are clear; no respiratory distress.']]},
resp:{patient:{name:'Morgan Lee',age:'46',pronouns:'he/him',historian:'Self; reliable',chief:'Persistent cough and exertional dyspnea',opening:'This cough will not go away, and I get winded walking upstairs.',behavior:'Concerned but cooperative.'},findings:[['hpi','Cough','Dry cough for ten days.'],['hpi','Dyspnea','Occurs with exertion but not at rest.'],['social','Exposure','A coworker recently had influenza.'],['ros','Pertinent negatives','No hemoptysis, cyanosis, syncope, or severe chest pain.'],['exam','Auscultation','Breath sounds are diminished at the right base.']]},
cardio:{patient:{name:'Alex Rivera',age:'52',pronouns:'he/him',historian:'Self; reliable',chief:'Exertional chest pressure',opening:'I have pressure in my chest whenever I hurry across the parking lot.',behavior:'Minimizes symptoms and wants to leave quickly.'},findings:[['hpi','Quality','Substernal pressure rather than sharp pain.'],['hpi','Provocation and relief','Occurs with exertion and resolves after several minutes of rest.'],['hpi','Associated symptom','Mild shortness of breath occurs during episodes.'],['family','Family risk','Father had a myocardial infarction at age 52.'],['ros','Current status','No pain at rest during this encounter.']]},
vascular:{patient:{name:'Casey Brooks',age:'38',pronouns:'she/her',historian:'Self; reliable',chief:'Unilateral leg swelling',opening:'My left leg has been swollen since yesterday.',behavior:'Anxious after reading about blood clots online.'},findings:[['hpi','Onset','Swelling began yesterday afternoon.'],['social','Risk factor','Returned from a long flight two days ago.'],['hpi','Pain','The calf is tender when walking.'],['ros','Pulmonary negatives','No chest pain, dyspnea, hemoptysis, or syncope.'],['exam','Extremity exam','Left calf is visibly larger with unilateral pitting edema.']]},
custom:{patient:{name:'',age:'',pronouns:'',historian:'Self; reliability to be determined',chief:'',opening:'',behavior:''},findings:[]}
};
const $=id=>document.getElementById(id);
let role=null,sessionCode=null,peer=null,conn=null,state=null;
let reconnectTimer=null,heartbeatTimer=null,lastPong=0,saveTimer=null,fieldTimer=null;
let pendingActions=[],coachPrivateNotes='';
function uid(prefix='id'){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
function cleanCode(value){return String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)}
function peerIdFor(code){return'nr509-clinical-lab-v3-'+code.toLowerCase()}
function stateKey(r,c){return`nr509-v3-state-${r}-${c}`}
function queueKey(c){return`nr509-v3-queue-${c}`}
function privateNotesKey(c){return`nr509-v3-private-notes-${c}`}
function defaultState(code,templateId='heent'){const t=templates[templateId];return{appVersion:APP_VERSION,sessionCode:code,templateId,currentStep:0,updatedAt:Date.now(),ended:false,patient:{...t.patient},completed:{},scores:{},released:{},findings:t.findings.map(([section,label,text])=>({id:uid('finding'),section,label,text})),feed:[{id:uid('system'),kind:'system',text:'Session created. Begin with identifying information and historian reliability.',ts:Date.now()}],studentNotes:'',processedActionIds:[]}}
function normalizeState(raw,code){const base=defaultState(code,'heent');if(!raw||typeof raw!=='object')return base;return{...base,...raw,patient:{...base.patient,...(raw.patient||{})},completed:raw.completed||{},scores:raw.scores||{},released:raw.released||{},findings:Array.isArray(raw.findings)?raw.findings:base.findings,feed:Array.isArray(raw.feed)?raw.feed:base.feed,processedActionIds:Array.isArray(raw.processedActionIds)?raw.processedActionIds:[]}}
function saveLocal(immediate=false){clearTimeout(saveTimer);const run=()=>{if(!role||!sessionCode||!state)return;localStorage.setItem(stateKey(role,sessionCode),JSON.stringify(state));localStorage.setItem(LAST_SESSION_KEY,JSON.stringify({role,code:sessionCode,ended:state.ended||false}));if(role==='coach'){localStorage.setItem(queueKey(sessionCode),JSON.stringify(pendingActions));localStorage.setItem(privateNotesKey(sessionCode),coachPrivateNotes)}$('saveStatus').textContent='Saved locally · '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'})};immediate?run():saveTimer=setTimeout(run,120)}
function loadLocal(r,c){try{return normalizeState(JSON.parse(localStorage.getItem(stateKey(r,c))),c)}catch(_){return defaultState(c)}}
function setStatus(text,type=''){$('statusText').textContent=text;$('statusDot').className='dot '+type}
function updateURL(r,c){const u=new URL(location.href);u.search='';u.searchParams.set('role',r);u.searchParams.set('code',c);history.replaceState({},'',u)}
function buildCoachLink(c){const u=new URL(location.href);u.search='';u.searchParams.set('role','coach');u.searchParams.set('code',c);return u.toString()}
function setLastSession(r,c,ended=false){localStorage.setItem(LAST_SESSION_KEY,JSON.stringify({role:r,code:c,ended}))}
function showLanding(){$('landing').classList.remove('hidden');$('waitingPanel').classList.add('hidden');$('appPanel').classList.add('hidden');renderResume()}
function showWaiting(message){$('landing').classList.add('hidden');$('appPanel').classList.add('hidden');$('waitingPanel').classList.remove('hidden');$('waitingRole').textContent=role==='student'?'NP Student':'Patient / Coach';$('sessionCode').textContent=sessionCode;$('waitingText').textContent=message;$('coachLink').textContent=role==='student'?buildCoachLink(sessionCode):'Using the saved patient/coach link for this session.';$('shareBtn').classList.toggle('hidden',role!=='student');$('copyBtn').classList.toggle('hidden',role!=='student')}
function showApp(){$('landing').classList.add('hidden');$('waitingPanel').classList.add('hidden');$('appPanel').classList.remove('hidden');$('studentView').classList.toggle('hidden',role!=='student');$('coachView').classList.toggle('hidden',role!=='coach');$('roleBadge').textContent=role==='student'?'NP Student':'Tutor / Professor / Patient';$('activeCode').textContent=sessionCode;renderAll()}
function renderResume(){let last=null;try{last=JSON.parse(localStorage.getItem(LAST_SESSION_KEY))}catch(_){last=null}const show=last&&last.code&&last.role&&!last.ended;$('resumeCard').classList.toggle('hidden',!show);if(show){$('resumeCode').textContent=last.code;$('resumeRoleText').textContent=last.role==='student'?'Resume as NP student.':'Resume as patient/coach.';$('resumeBtn').dataset.role=last.role;$('resumeBtn').dataset.code=last.code}}
function createSession(){role='student';sessionCode=randomCode();state=defaultState(sessionCode,'heent');updateURL(role,sessionCode);setLastSession(role,sessionCode,false);saveLocal(true);showWaiting('Creating the persistent live session…');startStudentHost()}
function resumeSession(r,c){role=r;sessionCode=cleanCode(c);state=loadLocal(role,sessionCode);updateURL(role,sessionCode);setLastSession(role,sessionCode,state.ended);showWaiting(role==='student'?'Restoring your saved session and waiting for the patient/coach…':'Restoring your saved patient/coach session and reconnecting…');if(role==='coach'){try{pendingActions=JSON.parse(localStorage.getItem(queueKey(sessionCode)))||[]}catch(_){pendingActions=[]}coachPrivateNotes=localStorage.getItem(privateNotesKey(sessionCode))||'';startCoachClient()}else startStudentHost()}
function joinSession(c){const code=cleanCode(c);if(code.length!==6){alert('Enter the six-character session code.');return}role='coach';sessionCode=code;state=loadLocal(role,code);updateURL(role,code);setLastSession(role,code,state.ended);try{pendingActions=JSON.parse(localStorage.getItem(queueKey(code)))||[]}catch(_){pendingActions=[]}coachPrivateNotes=localStorage.getItem(privateNotesKey(code))||'';showWaiting('Connecting to the student. This page will retry automatically.');startCoachClient()}
function destroyPeer(){clearTimeout(reconnectTimer);clearInterval(heartbeatTimer);if(conn){try{conn.close()}catch(_){}}if(peer){try{peer.destroy()}catch(_){}}conn=null;peer=null}
function startStudentHost(){destroyPeer();if(typeof Peer==='undefined'){setStatus('Connection library unavailable','error');showApp();return}setStatus('Starting session…','waiting');peer=new Peer(peerIdFor(sessionCode),{debug:0});peer.on('open',()=>{setStatus('Waiting for patient/coach','waiting');showApp()});peer.on('connection',incoming=>{if(conn&&conn.open){try{conn.close()}catch(_){}}setupConnection(incoming)});peer.on('disconnected',()=>{setStatus('Reconnecting host…','waiting');try{peer.reconnect()}catch(_){scheduleReconnect()}});peer.on('close',()=>{setStatus('Host connection closed','waiting');scheduleReconnect()});peer.on('error',err=>{if(err&&err.type==='unavailable-id'){setStatus('Restoring session ID…','waiting');scheduleReconnect(1800)}else{setStatus('Connection interrupted — retrying','waiting');scheduleReconnect()}})}
function startCoachClient(){destroyPeer();if(typeof Peer==='undefined'){setStatus('Connection library unavailable','error');showApp();return}setStatus('Connecting…','waiting');peer=new Peer(undefined,{debug:0});peer.on('open',()=>connectCoachToHost());peer.on('disconnected',()=>{setStatus('Reconnecting…','waiting');try{peer.reconnect()}catch(_){scheduleReconnect()}});peer.on('close',()=>{setStatus('Connection closed — retrying','waiting');scheduleReconnect()});peer.on('error',()=>{setStatus('Waiting for student — retrying','waiting');scheduleReconnect()})}
function connectCoachToHost(){if(!peer||peer.destroyed)return;setStatus('Connecting to student…','waiting');const c=peer.connect(peerIdFor(sessionCode),{reliable:true,serialization:'json'});setupConnection(c)}
function scheduleReconnect(delay=2500){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>{if(role==='student')startStudentHost();else startCoachClient()},delay)}
function setupConnection(connection){conn=connection;conn.on('open',()=>{lastPong=Date.now();setStatus(role==='student'?'Patient/coach connected':'Connected live','online');showApp();if(role==='student')sendState();else send({type:'hello',role:'coach',updatedAt:state.updatedAt,pendingActions});startHeartbeat()});conn.on('data',handleData);conn.on('close',()=>{setStatus('Disconnected — reconnecting automatically','waiting');scheduleReconnect(1200)});conn.on('error',()=>{setStatus('Connection error — retrying','waiting');scheduleReconnect(1500)})}
function startHeartbeat(){clearInterval(heartbeatTimer);heartbeatTimer=setInterval(()=>{if(conn&&conn.open){send({type:'ping',ts:Date.now()});if(Date.now()-lastPong>30000){try{conn.close()}catch(_){}}}},9000)}
function send(payload){if(conn&&conn.open){try{conn.send(payload);return true}catch(_){return false}}return false}
function sendState(){if(role==='student')send({type:'state',state})}
function handleData(data){if(!data||typeof data!=='object')return;if(data.type==='ping'){send({type:'pong',ts:data.ts});return}if(data.type==='pong'){lastPong=Date.now();return}if(role==='student'){if(data.type==='hello'){if(Array.isArray(data.pendingActions))applyActionBatch(data.pendingActions);sendState();return}if(data.type==='actions'){applyActionBatch(data.actions||[]);return}}else{if(data.type==='state'){state=normalizeState(data.state,sessionCode);saveLocal(true);renderAll();return}if(data.type==='ack'){const ids=new Set(data.ids||[]);pendingActions=pendingActions.filter(a=>!ids.has(a.id));saveLocal(true);return}}}
function applyActionBatch(actions){const applied=[];for(const action of actions){if(!action||!action.id||state.processedActionIds.includes(action.id))continue;applyActionToState(action);state.processedActionIds.push(action.id);applied.push(action.id)}state.processedActionIds=state.processedActionIds.slice(-150);if(applied.length){touchState();send({type:'ack',ids:applied});sendState()}}
function applyActionToState(action){const p=action.payload||{};switch(action.kind){case'setPatientField':state.patient[p.field]=p.value;break;case'setTemplate':applyTemplate(p.templateId);break;case'addFeed':state.feed.push({id:p.id||uid('msg'),kind:p.urgent?'patient urgent':'patient',text:p.text,ts:p.ts||Date.now(),urgent:!!p.urgent});break;case'setScore':state.scores[p.stepId]=p.value;break;case'setCurrentStep':state.currentStep=Math.max(0,Math.min(workflow.length-1,Number(p.index)||0));break;case'toggleRelease':state.released[p.findingId]=!!p.value;break;case'addFinding':state.findings.push(p.finding);break;case'updateFinding':{const f=state.findings.find(x=>x.id===p.id);if(f)f[p.field]=p.value}break;case'deleteFinding':state.findings=state.findings.filter(x=>x.id!==p.id);delete state.released[p.id];break;case'setEnded':state.ended=!!p.value;break}}
function coachAction(kind,payload){const action={id:uid('action'),kind,payload,ts:Date.now()};applyActionToState(action);pendingActions.push(action);touchState(false);saveLocal(true);renderAll();if(conn&&conn.open)send({type:'actions',actions:pendingActions})}
function studentUpdate(mutator){mutator();touchState();sendState();renderAll()}
function touchState(save=true){state.updatedAt=Date.now();if(save)saveLocal()}
function applyTemplate(templateId){const t=templates[templateId]||templates.custom;state.templateId=templateId;state.patient={...t.patient};state.findings=t.findings.map(([section,label,text])=>({id:uid('finding'),section,label,text}));state.released={};state.feed=[{id:uid('system'),kind:'system',text:'Patient template changed. Restart the encounter from identifying information.',ts:Date.now()}];state.completed={};state.scores={};state.currentStep=0;state.studentNotes=''}